export type GuideStep = { id:string; n:string; title:string; details:string[]; callout?:{title:string;text:string}; images?:string[]; detailImages?:string[][]; calloutImages?:string[]; defaultVideo?:string };

export const promptText = `Tôi cung cấp dịch vụ tư vấn dinh dưỡng 28 ngày cho người làm văn phòng, vận hành một mình. Hãy viết cho tôi một file Google Apps Script duy nhất thực hiện toàn bộ chuỗi từ lúc khách điền biểu mẫu đến khi tôi nhận được bản tóm tắt thư phản hồi.

Bối cảnh cài đặt: tôi sẽ tạo một Google Sheets trống, mở Apps Script từ chính bảng tính đó (Tiện ích mở rộng → Apps Script) và dán toàn bộ mã vào.

Ràng buộc bắt buộc:
- Dùng SpreadsheetApp.getActiveSpreadsheet(). Tuyệt đối không dùng SpreadsheetApp.create để tạo bảng tính mới.
- Có hàm onOpen tạo menu tên "Tư vấn AI" trên bảng tính, mỗi bước là một mục để tôi chạy tay và dễ gỡ lỗi.
- Khóa API đọc từ PropertiesService.getScriptProperties() với tên OPENAI_API_KEY. Không viết khóa trong mã.
- Tra cột theo tên tiêu đề, không dùng vị trí cột cố định.
- Mọi lệnh gọi API đặt muteHttpExceptions: true và ném lỗi kèm nguyên văn nội dung trả về.
- Đặt max_tokens ít nhất 4000 cho các lệnh sinh nội dung dài.
- Tên hàm, biến, chú thích và thông báo đều bằng tiếng Việt.

Năm trang tính: KHACH_HANG (do biểu mẫu tạo ra, thêm cột Mã khách), AI_DU_THAO, KE_HOACH_CUOI, PHAN_HOI_EMAIL, CAU_HINH. Trang CAU_HINH lưu bốn câu lệnh gửi AI kèm cột phiên bản và ngày cập nhật; mã phải đọc câu lệnh từ trang này, không viết cứng trong code.

Các chức năng cần có, mỗi chức năng là một mục trong menu:
1. Tạo khung trang tính — tạo bốn trang tính kèm hàng tiêu đề, điền sẵn bốn câu lệnh vào CAU_HINH.
2. Tạo biểu mẫu — dùng FormApp tạo Google Form thu: thông tin liên hệ, nhịp làm việc và sinh hoạt, thói quen ăn uống hiện tại, ràng buộc và sở thích, mục tiêu, và phần sàng lọc các trường hợp cần chuyển sang chuyên môn y tế (thai kỳ, đang điều trị bệnh, tiền sử rối loạn ăn uống). Nối phản hồi về bảng tính đang mở, đổi tên trang phản hồi thành KHACH_HANG, thêm cột Mã khách. In ra đường dẫn biểu mẫu.
3. Tạo bản dự thảo — đọc một dòng khách, bỏ các cột nhận diện (họ tên, email, số điện thoại), gửi phần còn lại sang OpenAI API. Yêu cầu trả về JSON gồm: tóm tắt tình trạng, thông tin còn thiếu, câu hỏi cần trao đổi, các điểm cần người tư vấn kiểm tra, và kế hoạch dự thảo 4 tuần dạng mảng đối tượng có tuần, mục tiêu, việc cần làm, tần suất, cách tự ghi nhận. Ghi vào AI_DU_THAO với trạng thái "Chờ duyệt". Tạo danh sách xổ ba giá trị Chờ duyệt / Cần sửa / Đồng ý cho cột Trạng thái duyệt 1.
4. Sửa theo góp ý — với các dòng trạng thái "Cần sửa" có nội dung trong cột Góp ý, gửi bản dự thảo kèm góp ý sang AI để viết lại. Chỉ sửa phần được góp ý, giữ nguyên phần còn lại, và liệt kê những gì đã thay đổi.
5. Chuyển sang bảng kế hoạch hoàn chỉnh — với các dòng "Đồng ý", ghi sang KE_HOACH_CUOI với trạng thái "Chờ duyệt cuối", kèm danh sách xổ hai giá trị Chờ duyệt cuối / Đã duyệt gửi.
6. Gửi kế hoạch qua Gmail — chỉ gửi với dòng có trạng thái đúng bằng "Đã duyệt gửi" và chưa có thời điểm gửi. Tiêu đề thư chứa mã khách, không chứa thông tin sức khỏe. Ghi lại thời điểm gửi để không gửi trùng.
7. Đọc thư phản hồi — tìm thư trả lời của khách theo mã khách trong tiêu đề, gửi nội dung sang AI để tóm tắt thành bốn mục: khách đã thực hiện được gì, khó khăn, câu hỏi của khách, điểm cần người tư vấn xem. Ghi vào PHAN_HOI_EMAIL rồi đánh dấu thư đã đọc.
8. Kiểm tra kết nối API — gọi một lệnh ngắn để xác nhận khóa và tên mô hình đúng.

Hai kích hoạt cần hướng dẫn cài: chạy khi biểu mẫu được gửi, và chạy theo lịch để đọc thư phản hồi.

Nguyên tắc chuyên môn ràng buộc trong câu lệnh gửi AI: không chẩn đoán bệnh, không kê thuốc, không suy diễn dữ liệu còn thiếu, không tự trả lời thay người tư vấn. Nội dung chưa đủ thông tin phải chuyển sang mục cần người tư vấn kiểm tra.

Xử lý lỗi: nếu AI trả về nội dung không phải JSON hợp lệ, ghi nguyên văn nội dung thô vào một cột để tôi đọc, không làm hỏng bảng.

Cuối cùng, hướng dẫn tôi dán mã ở đâu, chạy hàm nào trước, cần cấp những quyền gì, và kiểm tra từng bước đã chạy đúng bằng cách nào.`;

export const steps: GuideStep[] = [
  {id:"buoc-chuan-bi",n:"00",title:"Tạo file Google Sheets trung tâm",details:["Mở Google, tìm Google Sheets và chọn trang chính thức của Google Trang tính.","Tạo một bảng tính trống, sau đó đổi tên file thành HE THONG TU VAN DINH DUONG 28 NGAY. Đây là file trung tâm; các trang tính nghiệp vụ sẽ được mã tự tạo ở bước sau."],detailImages:[["m1-s00-01.jpg"],["m1-s00-02.jpg"]],defaultVideo:"/steps/videos/model1/buoc-00.mp4"},
  {id:"buoc-1",n:"01",title:"Lấy mã hệ thống và đưa vào Apps Script",details:["Mở cuộc trò chuyện với ChatGPT hoặc Claude và gửi câu lệnh tạo hệ thống. Nếu đã có bộ mã chuẩn trên website này, bạn có thể dùng trực tiếp để tránh sai tên hàm hoặc thiếu chức năng.","Kiểm tra kết quả AI trả về và xác định đúng phần mã Apps Script chính. Sao chép trọn vẹn mã, không lấy lẫn phần giải thích ở bên ngoài khung mã.","Quay lại Google Sheets trung tâm, mở Tiện ích mở rộng và chọn Apps Script.","Trong tệp Code.gs, xóa hàm mẫu, dán toàn bộ mã hệ thống rồi nhấn Lưu. Không tạo một bảng tính mới trong mã vì hệ thống phải làm việc với chính file đang mở."],detailImages:[["m1-s01-01.jpg"],["m1-s01-02.jpg"],["m1-s01-03.jpg"],["m1-s01-04.jpg","m1-extra-s01-04.jpg"]],defaultVideo:"/steps/videos/model1/buoc-01.mp4"},
  {id:"buoc-2",n:"02",title:"Kết nối API, thanh toán, tạo biểu mẫu và sinh bản dự thảo",details:["Đăng nhập nền tảng API tương ứng với loại mã đang dùng. Video minh họa sử dụng OpenAI API.","Trước khi tạo khóa API, mở Billing. Tại Payment methods, thêm phương thức thanh toán nếu tài khoản chưa có thẻ. Đây là phần thanh toán riêng của OpenAI API, không phải phí gói ChatGPT.","Trong Billing, chọn Buy credits, nhập số tiền muốn nạp, kiểm tra phương thức thanh toán rồi chọn Continue để xác nhận. Số tiền tối thiểu, giá mô hình và tên nút có thể thay đổi theo giao diện tại thời điểm sử dụng.","Mở API keys, chọn tạo khóa bí mật mới, đặt tên để dễ nhận biết rồi sao chép khóa ngay khi hệ thống hiển thị. Khóa chỉ xuất hiện đầy đủ một lần.","Trở lại Apps Script, mở Cài đặt dự án và thêm Thuộc tính của tập lệnh. Tên thuộc tính là OPENAI_API_KEY; ô giá trị là khóa vừa sao chép. Không dán khóa trực tiếp vào mã.","Kiểm tra phần Tổng quan dự án để chắc chắn dự án Apps Script đang gắn với đúng bảng tính trung tâm.","Quay lại Google Sheets, tải lại trang và mở menu Tư vấn AI. Lần chạy đầu, chọn chức năng kiểm tra API và hoàn tất các màn hình cấp quyền của Google.","Khi thông báo kết nối API thành công xuất hiện, hệ thống đã sẵn sàng gọi AI.","Trong menu Tư vấn AI, chạy Tạo khung trang tính. Hệ thống tạo các trang AI_DU_THAO, KE_HOACH_CUOI, PHAN_HOI_EMAIL và CAU_HINH mà không xóa dữ liệu hiện có.","Chạy Tạo biểu mẫu thu thập thông tin. Hệ thống tạo Google Form, kết nối phản hồi về file trung tâm và trả đường dẫn để bạn mở hoặc gửi cho khách.","Điền một phiếu thử như khách hàng thật và gửi biểu mẫu. Kiểm tra dữ liệu mới đã xuất hiện trong trang KHACH_HANG.","Chọn dòng khách vừa tạo, mở menu Tư vấn AI và chạy Tạo bản dự thảo cho dòng đang chọn. Kết quả được ghi vào AI_DU_THAO với trạng thái Chờ duyệt."],callout:{title:"Kết quả của bước này",text:"Một hồ sơ dự thảo gồm mã khách, tóm tắt tình trạng, thông tin còn thiếu, điểm cần người tư vấn kiểm tra, câu hỏi cần trao đổi và kế hoạch bốn tuần. AI không được chẩn đoán, kê thuốc hoặc tự suy diễn dữ liệu chưa có."},detailImages:[["m1-s02-01.jpg"],["m1-payment-01.png"],["m1-payment-02.png"],["m1-extra-s02-01.jpg","m1-extra-s02-02.jpg"],["m1-extra-s02-03.jpg","m1-s02-04.jpg"],["m1-s02-05.jpg"],["m1-extra-s02-04.jpg","m1-s02-06.jpg"],["m1-s02-07.jpg"],["m1-s02-08.jpg"],["m1-extra-s02-07.jpg","m1-s02-09.jpg"],["m1-extra-s02-09.jpg","m1-extra-s02-10.jpg"],["m1-s02-11.jpg"]],defaultVideo:"/steps/videos/model1/buoc-02.mp4"},
  {id:"buoc-3",n:"03",title:"Người tư vấn duyệt bản dự thảo lần thứ nhất",details:["Mở AI_DU_THAO và đọc toàn bộ bản dự thảo của đúng mã khách. Đối chiếu với dữ liệu gốc để phát hiện nội dung AI đọc sai hoặc suy diễn quá dữ kiện.","Nếu cần điều chỉnh, nhập yêu cầu cụ thể vào cột Góp ý và đổi Trạng thái duyệt 1 thành Cần sửa.","Nếu bản dự thảo đã phù hợp, chọn Đồng ý. Chỉ những dòng có trạng thái Đồng ý mới được chuyển sang bảng kế hoạch hoàn chỉnh."],callout:{title:"Ba nội dung phải kiểm tra",text:"Dữ liệu khách có được đọc đúng không; nội dung có vượt quá phạm vi tư vấn không; mục tiêu và kế hoạch có phù hợp với điều đã trao đổi không."},detailImages:[["m1-s03-01.jpg"],["m1-s03-02.jpg"],["m1-s03-03.jpg"]],defaultVideo:"/steps/videos/model1/buoc-03.mp4"},
  {id:"buoc-4",n:"04",title:"Sửa theo góp ý và chuyển sang kế hoạch hoàn chỉnh",details:["Với dòng có trạng thái Cần sửa và đã có góp ý, chạy chức năng Sửa theo góp ý. AI chỉ sửa phần được yêu cầu và giữ nguyên phần còn lại.","Đọc lại nội dung sau khi AI cập nhật, đặc biệt là phần AI liệt kê những thay đổi đã thực hiện.","Khi nội dung đã đạt yêu cầu, chọn Đồng ý và chạy Chuyển sang bảng kế hoạch hoàn chỉnh. Hệ thống ghi kết quả vào KE_HOACH_CUOI với trạng thái Chờ duyệt cuối."],callout:{title:"Kết quả cần có",text:"Bảng kế hoạch nêu rõ tuần hoặc ngày, mục tiêu, việc cần làm, tần suất, cách tự ghi nhận và những trường hợp khách cần báo lại cho người tư vấn."},detailImages:[["m1-extra-s04-01.jpg"],["m1-s04-02.jpg"],["m1-extra-s04-03.jpg"]],defaultVideo:"/steps/videos/model1/buoc-04.mp4"},
  {id:"buoc-5",n:"05",title:"Duyệt bản cuối trước khi gửi khách",details:["Mở KE_HOACH_CUOI, đọc lại toàn bộ bản kế hoạch và đối chiếu với bản đã duyệt ở bước trước.","Chỉ khi chịu trách nhiệm về nội dung cuối, đổi trạng thái thành Đã duyệt gửi. Nếu còn điểm chưa chắc chắn, giữ Chờ duyệt cuối và quay lại bước sửa."],callout:{title:"Điểm chặn bắt buộc",text:"Hệ thống không được gửi kế hoạch chỉ vì AI đã hoàn thành nội dung. Trạng thái Đã duyệt gửi phải do người tư vấn chủ động chọn."},detailImages:[["m1-extra-s05-01.jpg"],["m1-s05-02.jpg"]],defaultVideo:"/steps/videos/model1/buoc-05.mp4"},
  {id:"buoc-6",n:"06",title:"Gửi kế hoạch đã duyệt qua Gmail",details:["Chọn dòng kế hoạch có trạng thái Đã duyệt gửi, mở menu Tư vấn AI và chạy Gửi kế hoạch qua Gmail.","Đọc hộp xác nhận trước khi gửi để tránh gửi nhầm khách hoặc gửi lại một hồ sơ đã xử lý.","Mở Gmail kiểm tra thư đã gửi. Tiêu đề nên chứa mã khách, không đưa thông tin sức khỏe nhạy cảm vào tiêu đề.","Trở lại KE_HOACH_CUOI và kiểm tra thời điểm gửi đã được ghi. Dấu thời gian này giúp hệ thống không gửi trùng."],callout:{title:"Nội dung thư",text:"Thư chỉ sử dụng kế hoạch đã được duyệt; không yêu cầu AI tạo một phương án tư vấn mới ngay tại bước gửi."},detailImages:[["m1-s06-01.jpg"],["m1-s06-02.jpg"],["m1-s06-03.jpg"],["m1-s06-04.jpg"]],defaultVideo:"/steps/videos/model1/buoc-06.mp4"},
  {id:"buoc-7",n:"07",title:"Đọc, phân loại và xử lý thư phản hồi của khách",details:["Khi nâng cấp hệ thống để xử lý phản hồi, thay mã Code.gs bằng phiên bản mới có đầy đủ luồng đọc thư, phân loại, soạn nháp trả lời và điều chỉnh kế hoạch. Lưu mã trước khi chạy.","Chạy lại Tạo khung trang tính một lần. Phiên bản mới chỉ bổ sung các cột cần thiết vào cuối bảng, không xóa dữ liệu cũ.","Kiểm tra các trang tính đã có thêm trường trạng thái phản hồi, nội dung cần duyệt, nội dung trả lời và ghi chú xử lý.","Khách trả lời trong đúng chuỗi Gmail có mã khách ở tiêu đề. Hệ thống dùng mã này để nối thư với hồ sơ tương ứng.","Trong menu Tư vấn AI, chạy chức năng đọc thư phản hồi mới. Hệ thống lấy phần thư chưa xử lý và gửi AI để tóm tắt, không tự trả lời khách.","Mở PHAN_HOI_EMAIL và kiểm tra bốn nhóm thông tin: khách đã làm được gì, khó khăn, câu hỏi và điểm cần người tư vấn xem.","Nếu cần trả lời, chạy chức năng soạn dự thảo trả lời, đọc lại và duyệt. Nếu khách yêu cầu điều chỉnh kế hoạch, chuyển hồ sơ về vòng sửa kế hoạch thay vì trả lời vội qua email.","Chỉ gửi thư trả lời sau khi người tư vấn đã duyệt nội dung. Kiểm tra trạng thái và thời điểm gửi để không gửi trùng."],callout:{title:"Nguyên tắc xử lý phản hồi",text:"AI có nhiệm vụ đọc, tóm tắt, phân loại và soạn nháp. Quyết định chuyên môn, thay đổi kế hoạch và nội dung gửi khách vẫn phải do người tư vấn duyệt."},detailImages:[["m1-s07-01.jpg"],["m1-s07-02.jpg"],["m1-s07-03.jpg"],["m1-s07-04.jpg"],["m1-extra-s07-05.jpg"],["m1-s07-06.jpg"],["m1-extra-s07-07.jpg"],["m1-s07-08.jpg"]],defaultVideo:"/steps/videos/model1/buoc-07.mp4"},
  {id:"buoc-8",n:"08",title:"Cập nhật menu sau khi bổ sung tính năng",details:["Sau khi thêm tính năng hoặc thay phiên bản mã, mở Code.gs và kiểm tra hàm onOpen đã có đầy đủ các mục menu mới.","Trên thanh công cụ Apps Script, chọn hàm onOpen rồi nhấn Chạy. Thao tác này tạo lại menu Tư vấn AI theo mã mới nhất.","Quay lại Google Sheets, tải lại trang và mở menu Tư vấn AI. Kiểm tra các chức năng mới đã xuất hiện đúng tên và đúng thứ tự.","Nếu Google yêu cầu quyền ở lần chạy đầu, chọn Tiếp tục, chọn đúng tài khoản, mở Nâng cao và cho phép dự án chạy."],callout:{title:"Khi nào cần làm lại?",text:"Khi thêm, đổi tên hoặc xóa chức năng; khi đã thay mã nhưng bảng tính vẫn hiện menu cũ; hoặc khi chuyển mã sang một bảng tính mới."},detailImages:[["m1-s08-01.jpg"],["m1-s08-02.jpg"],["m1-extra-s08-01.jpg"],["m1-extra-s08-02.jpg"]],defaultVideo:"/steps/videos/model1/buoc-09.mp4"},
  {id:"buoc-9",n:"09",title:"Tạo và mở Dashboard điều phối",details:["Trong cuộc trò chuyện đang dùng, yêu cầu AI tạo Dashboard dựa trên đúng các trang tính và chức năng của phiên bản mã hiện tại. Dashboard chỉ tổng hợp dữ liệu, không tạo một kho dữ liệu riêng.","Trong Apps Script, nhấn dấu cộng ở mục Tệp, chọn HTML, đặt tên Dashboard và dán phần mã giao diện HTML.","Nhấn dấu cộng lần nữa, chọn Tập lệnh, đặt tên Webapp. Không đặt trùng tên Dashboard.","Dán phần mã Apps Script dùng để đọc số liệu, xử lý nút bấm và mở bảng điều khiển; sau đó lưu toàn bộ dự án.","Từ menu Tư vấn AI, chọn mở bảng điều khiển. Dashboard mới hiển thị bốn nhóm ưu tiên ở đầu màn hình và các cụm thao tác phía dưới để người tư vấn xử lý hồ sơ theo đúng vòng làm việc."],callout:{title:"Bốn nhóm ưu tiên trên Dashboard",text:"Cần bạn duyệt; sẵn sàng gửi; phản hồi ưu tiên cao; chờ AI xử lý. Số liệu phải khớp với các trạng thái đang có trong Google Sheets."},detailImages:[["m1-extra-s09-01.jpg"],["m1-extra-s09-02.jpg"],["m1-extra-s09-03.jpg"],["m1-extra-s09-04.jpg"],["m1-s09-05.jpg"]],defaultVideo:"/steps/videos/model1/buoc-08.mp4"}
];

export const knowledgeText = steps.map(s=>`${s.n}. ${s.title}\n${s.details.join("\n")}\n${s.callout?`${s.callout.title}: ${s.callout.text}`:""}`).join("\n\n");

