import type { GuideStep } from "./knowledge";

export const promptText2 = `Tôi cung cấp dịch vụ "12 video ngắn mỗi tháng" cho doanh nghiệp nhỏ, vận hành một mình. Khách không quay video; khách chỉ nộp ảnh sản phẩm, ảnh chân dung nhân vật đại diện và tệp logo, còn tôi dùng AI dựng toàn bộ cảnh từ chính bộ ảnh đó rồi trả video về thư mục của khách. Hãy viết cho tôi mã Google Apps Script thực hiện toàn bộ chuỗi từ lúc khách điền biểu mẫu đến khi tôi phân loại xong thư phản hồi.

Bối cảnh cài đặt: tôi tạo một Google Sheets trống, mở Apps Script từ chính bảng tính đó và dán mã vào. Cần đúng ba tệp, viết đầy đủ trong một câu trả lời, mỗi tệp một khối mã có ghi tên: Ma.gs chứa nghiệp vụ và menu, bang_dieu_khien.gs chứa phần máy chủ của bảng điều khiển, bang_dieu_khien.html chứa giao diện.

Ràng buộc bắt buộc:
- Dùng SpreadsheetApp.getActiveSpreadsheet(). Tuyệt đối không dùng SpreadsheetApp.create.
- Chỉ Ma.gs được khai báo onOpen, tạo menu "San xuat video", mỗi bước là một mục để tôi chạy tay. Mục mở bảng điều khiển nằm luôn trong menu này. Hai tệp cùng khai báo onOpen sẽ ghi đè nhau và một menu biến mất.
- Mọi tên hàm mà tệp HTML gọi phải thật sự tồn tại trong hai tệp .gs. Cuối câu trả lời liệt kê bảng đối chiếu.
- Khóa API đọc từ PropertiesService.getScriptProperties() với tên OPENAI_API_KEY. Không viết khóa trong mã.
- Tra cột theo tên tiêu đề, không dùng vị trí cột cố định.
- Mọi lệnh gọi API đặt muteHttpExceptions: true và ném lỗi kèm nguyên văn nội dung trả về. max_tokens ít nhất 4000.
- Mỗi lần chạy xử lý tối đa 4 video và tự dừng khi quá 270 giây, vì Apps Script giới hạn 6 phút.
- Tên hàm và biến viết tiếng Việt không dấu; chú thích, thông báo và câu lệnh gửi AI viết tiếng Việt có dấu.

Chín trang tính: KHACH_HANG (do biểu mẫu tạo ra, thêm cột hệ thống), HO_SO, Y_TUONG, KICH_BAN, KE_HOACH_HINH, SAN_XUAT, PHAN_HOI, SO_LIEU, CAU_HINH. Trang CAU_HINH lưu năm câu lệnh gửi AI cùng các tham số mô hình, ngưỡng ảnh tối thiểu, mẫu thư và tiêu chuẩn ảnh; mã phải đọc từ trang này, không viết cứng trong code.

Cột hệ thống thêm vào KHACH_HANG: MA_KH, LINK_DRIVE, LINK_ANH_GOC, LINK_VIDEO_FINAL, TRANG_THAI, MA_DOT_GIAO, SO_VIDEO_DOT, SO_ANH_SAN_PHAM, SO_ANH_NHAN_VAT, SO_LOGO, NGAY_GUI_LINK_ANH, DUYET_Y_TUONG, DUYET_KICH_BAN, DUYET_CUOI, NGAY_GIAO, GHI_CHU_HE_THONG. Ba cột duyệt gắn danh sách xổ để tôi chọn thay vì gõ tay.

Các chức năng cần có, mỗi chức năng là một mục trong menu:
1. Tạo khung trang tính — tạo các trang kèm hàng tiêu đề, gieo sẵn cấu hình và câu lệnh vào CAU_HINH.
2. Tạo biểu mẫu — dùng FormApp thu: email nhận bàn giao, tên doanh nghiệp, ngành nghề và khu vực, dịch vụ đang bán, nhóm khách mục tiêu, ba vấn đề khách thường gặp, bảng giá, bằng chứng được phép dùng, câu không được phép cam kết, phong cách thương hiệu, danh sách sản phẩm cần lên hình, mô tả nhân vật đại diện, xác nhận quyền sử dụng hình ảnh. Nối phản hồi về bảng tính đang mở, đổi tên trang phản hồi thành KHACH_HANG. Lưu ý FormApp không có addFileUploadItem nên biểu mẫu chỉ thu phần chữ.
3. Tạo thư mục và gửi liên kết nộp ảnh — tạo 03_ANH_KHACH_GUI với ba thư mục con SAN_PHAM, NHAN_VAT, LOGO, và 04_VIDEO_FINAL. Chỉ mở quyền chỉnh sửa cho riêng thư mục ảnh, không mở trên thư mục gốc để khách không thấy video chưa duyệt. Gửi thư kèm liên kết và tiêu chuẩn ảnh.
4. Đếm ảnh khách đã nộp — đếm tệp trong ba thư mục con, đủ ngưỡng thì hạ quyền về chỉ xem để bộ ảnh không đổi giữa chừng.
5. Kiểm tra hồ sơ đầu vào — gửi dữ liệu biểu mẫu kèm bảng kiểm kê ảnh sang AI, trả về JSON gồm tóm tắt doanh nghiệp, dữ liệu còn thiếu, nội dung chưa có bằng chứng, và trạng thái CAN_BO_SUNG hoặc DU_DU_LIEU. Thiếu ảnh thì luôn là CAN_BO_SUNG bất kể AI kết luận thế nào.
6. Gửi thư yêu cầu bổ sung — ghép từ dữ liệu bảng tính và mẫu thư, không dùng AI soạn thư gửi khách.
7. Tạo 20 góc nội dung — chỉ đề xuất góc dựng được từ ảnh khách đã nộp, không đề xuất góc cần quay tại cơ sở hay cần khách hàng thật xuất hiện. Ghi vào Y_TUONG kèm danh sách xổ DUYET / LOAI.
8. Viết kịch bản — chỉ chạy khi cột DUYET_Y_TUONG bằng "Đã duyệt". Viết cho các ý tưởng đã đánh DUYET và chưa có kịch bản.
9. Tạo kế hoạch hình — chỉ chạy khi cột DUYET_KICH_BAN bằng "Đã duyệt". AI được cung cấp danh sách tên tệp ảnh thật và chỉ được chọn ảnh tham chiếu trong danh sách đó; mã phải tự kiểm tra lại, tên tệp không có thật thì ghi đè thành THIEU_ANH kèm ghi chú. Bốn loại cảnh: CANH_SAN_PHAM, CANH_NHAN_VAT, CANH_MINH_HOA, CANH_DO_HOA. Công cụ chỉ nhận VEO, SEEDANCE, CAPCUT.
10. Ghi kết quả QC — đối chiếu danh sách video với tệp thực tế trong 04_VIDEO_FINAL, giữ nguyên các cột QC tôi đã điền tay.
11. Bàn giao qua Gmail — chỉ gửi khi cột DUYET_CUOI đúng bằng "Đã duyệt gửi" và khi đếm đủ số video của đợt. Ghi lại ngày giao để không gửi trùng.
12. Đọc thư phản hồi — tìm thư theo mã khách trong tiêu đề, gửi sang AI phân loại thành LOI_CUNG_CAP, TRONG_VONG_SUA hoặc PHAT_SINH kèm lý do và hành động đề xuất, rồi gắn nhãn thư đã xử lý.
13. Kiểm tra kết nối API — gọi một lệnh ngắn để xác nhận khóa và tên mô hình.
14. Mở bảng điều khiển — hộp thoại HTML hiện mọi khách xếp theo tám chặng đang mắc, mỗi khách một thẻ có thanh tiến độ, câu "việc tiếp theo" và nút chạy bước đó. Hàm lấy dữ liệu chỉ đọc trang tính, không gọi Drive và không gọi API để mở nhanh. Hàm chạy bước phải trỏ con trỏ về đúng dòng bằng setActiveSheet và setActiveRange trước khi gọi hàm nghiệp vụ, và dùng switch liệt kê tường minh chứ không dùng eval.

Ba kích hoạt cần hướng dẫn cài: chạy khi biểu mẫu được gửi, đếm ảnh mỗi 4 giờ, đọc thư phản hồi mỗi 4 giờ.

Nguyên tắc ràng buộc trong câu lệnh gửi AI: không bịa số liệu, thành tích, giải thưởng hay lời chứng thực; nội dung chưa có bằng chứng phải gắn nhãn CAN_XAC_NHAN; không thay mặt tôi trả lời khách; không báo giá, không cam kết kết quả; thiếu dữ liệu thì ghi rõ là thiếu, không suy đoán.

Xử lý lỗi: AI trả về không phải JSON hợp lệ thì ghi nguyên văn vào cột JSON_THO để tôi đọc, không làm hỏng bảng và không dừng cả vòng lặp. Hàm thay biến trong mẫu thư dùng split().join() chứ không dùng replace, vì ký tự $ trong bảng giá sẽ làm hỏng chuỗi.

Cuối cùng, hướng dẫn tôi dán từng tệp ở đâu, chạy hàm nào trước, cần cấp những quyền gì, và kiểm tra từng bước đã chạy đúng bằng cách nào.`;

export const steps2: GuideStep[] = [
  {id:"m2-buoc-01",n:"01",title:"Tạo bảng tính trung tâm và cài đủ ba tệp mã",details:["Tạo một Google Sheets trống và đổi tên thành hệ thống sản xuất video. Đây là tệp trung tâm chứa toàn bộ hồ sơ khách, ý tưởng, kịch bản, kế hoạch hình và kết quả sản xuất.","Mở Tiện ích mở rộng → Apps Script. Trong dự án, tạo đúng ba tệp: Ma.gs, bang_dieu_khien.gs và bang_dieu_khien.html.","Dán đúng nội dung vào từng tệp rồi lưu. Chỉ Ma.gs được có hàm onOpen; không tạo thêm một onOpen trong tệp bảng điều khiển."],callout:{title:"Kết quả của bước",text:"Dự án Apps Script đã có đủ ba tệp và không bị trùng hàm onOpen. Menu của hệ thống sẽ được tạo từ Ma.gs."},detailImages:[["m2-01.jpg"],["m2-02.jpg","m2-03.jpg"],["m2-03.jpg"]],calloutImages:[],defaultVideo:"/steps/videos/model2/full-a-z.mp4#t=0,100"},
  {id:"m2-buoc-02",n:"02",title:"Kết nối OpenAI API và cấp quyền cho hệ thống",details:["Mở OpenAI Platform, vào API Keys, tạo khóa bí mật mới và sao chép khóa ngay khi hệ thống hiển thị.","Trong Apps Script, mở Cài đặt dự án. Tại Thuộc tính của tập lệnh, thêm OPENAI_API_KEY và dán khóa vào ô giá trị.","Quay lại trình chỉnh sửa, chọn hàm cần chạy lần đầu và nhấn Chạy. Hoàn tất các màn hình chọn tài khoản, mở phần nâng cao và cấp quyền cho dự án.","Trở lại Google Sheets và tải lại trang. Kiểm tra menu San xuat video đã xuất hiện; chạy Kiểm tra kết nối API để xác nhận cấu hình."],callout:{title:"Lưu ý bảo mật",text:"Không ghi khóa API trực tiếp trong mã và không chia sẻ khóa cho người khác. Video không quay phần thanh toán OpenAI; nếu tài khoản chưa có số dư, cần bổ sung Billing trước khi gọi API."},detailImages:[["m2-04.jpg"],["m2-05.jpg"],["m2-06.jpg"],["m2-08.jpg"]],calloutImages:[],defaultVideo:"/steps/videos/model2/full-a-z.mp4#t=100,220"},
  {id:"m2-buoc-03",n:"03",title:"Tạo khung trang tính, biểu mẫu và hồ sơ khách hàng",details:["Trong menu San xuat video, chạy Tạo khung trang tính. Hệ thống tạo HO_SO, Y_TUONG, KICH_BAN, KE_HOACH_HINH, SAN_XUAT, PHAN_HOI, SO_LIEU và CAU_HINH.","Chạy Tạo biểu mẫu. Mở liên kết biểu mẫu và kiểm tra đầy đủ các câu hỏi về doanh nghiệp, khách hàng mục tiêu, sản phẩm, bằng chứng và phong cách thương hiệu.","Điền một hồ sơ thử nghiệm rồi gửi. Quay lại KHACH_HANG và kiểm tra dòng dữ liệu mới cùng các cột hệ thống đã được thêm."],callout:{title:"Biểu mẫu chỉ thu phần chữ",text:"FormApp không tạo được câu hỏi tải tệp bằng addFileUploadItem. Ảnh sản phẩm, ảnh nhân vật và logo sẽ được khách nộp qua thư mục Drive ở bước tiếp theo."},detailImages:[["m2-09.jpg"],["m2-10.jpg","m2-11.jpg"],["m2-12.jpg"]],calloutImages:[],defaultVideo:"/steps/videos/model2/full-a-z.mp4#t=220,315"},
  {id:"m2-buoc-04",n:"04",title:"Tạo thư mục, gửi liên kết và nhận bộ ảnh của khách",details:["Chọn dòng khách hàng, chạy Tạo thư mục và gửi liên kết nộp ảnh. Hệ thống tạo 03_ANH_KHACH_GUI với ba thư mục con SAN_PHAM, NHAN_VAT, LOGO và tạo riêng 04_VIDEO_FINAL.","Mở Gmail kiểm tra thư gửi khách. Thư phải có liên kết nộp ảnh và tiêu chuẩn ảnh lấy từ CAU_HINH.","Mở thư mục ảnh và tải đúng loại tệp vào từng thư mục con: logo vào LOGO, ảnh chân dung vào NHAN_VAT, ảnh sản phẩm vào SAN_PHAM.","Chạy Đếm ảnh khách đã nộp. Khi đủ ngưỡng, hệ thống ghi số lượng vào KHACH_HANG và hạ quyền thư mục ảnh về chỉ xem để dữ liệu không thay đổi giữa chừng."],callout:{title:"Quyền truy cập Drive",text:"Chỉ thư mục 03_ANH_KHACH_GUI được mở quyền chỉnh sửa cho khách. Không mở quyền trên thư mục gốc để khách không nhìn thấy video đang sản xuất hoặc video chưa duyệt."},detailImages:[["m2-13.jpg"],["m2-14.jpg"],["m2-15.jpg","m2-16.jpg","m2-17.jpg"],["m2-18.jpg"]],calloutImages:[],defaultVideo:"/steps/videos/model2/full-a-z.mp4#t=315,475"},
  {id:"m2-buoc-05",n:"05",title:"Kiểm tra hồ sơ đầu vào và yêu cầu bổ sung",details:["Chọn dòng khách và chạy Kiểm tra hồ sơ đầu vào. Hệ thống gửi dữ liệu biểu mẫu cùng bảng kiểm kê ảnh sang AI.","Mở HO_SO và kiểm tra phần tóm tắt doanh nghiệp, dữ liệu còn thiếu, nội dung chưa có bằng chứng và trạng thái hồ sơ.","Nếu trạng thái là CAN_BO_SUNG, chạy Gửi thư yêu cầu bổ sung. Nội dung thư được ghép từ mẫu và dữ liệu bảng tính, không dùng AI tự soạn thư gửi khách."],callout:{title:"Điểm chặn bắt buộc",text:"Nếu thiếu ảnh so với ngưỡng cấu hình, hồ sơ luôn phải là CAN_BO_SUNG, kể cả khi AI trả về DU_DU_LIEU."},detailImages:[["m2-19.jpg"],["m2-20.jpg","m2-21.jpg"],["m2-14.jpg"]],calloutImages:[],defaultVideo:"/steps/videos/model2/full-a-z.mp4#t=475,540"},
  {id:"m2-buoc-06",n:"06",title:"Tạo và duyệt 20 góc nội dung",details:["Khi hồ sơ đủ dữ liệu, chạy Tạo 20 góc nội dung. AI chỉ được đề xuất những góc có thể dựng từ bộ ảnh khách đã nộp.","Mở Y_TUONG, đọc từng góc nội dung và kiểm tra thông điệp, bằng chứng, loại cảnh dự kiến và nội dung cần xác nhận.","Tại từng dòng ý tưởng, chọn DUYET hoặc LOAI. Sau khi hoàn tất, đổi DUYET_Y_TUONG trên KHACH_HANG thành Đã duyệt."],callout:{title:"Không đề xuất cảnh không thể sản xuất",text:"Không sử dụng góc cần quay tại cơ sở, cần khách hàng thật xuất hiện hoặc cần bằng chứng chưa được cung cấp."},detailImages:[["m2-22.jpg"],["m2-23.jpg"],["m2-24.jpg"]],calloutImages:[],defaultVideo:"/steps/videos/model2/full-a-z.mp4#t=540,620"},
  {id:"m2-buoc-07",n:"07",title:"Viết và duyệt kịch bản video",details:["Chỉ sau khi DUYET_Y_TUONG bằng Đã duyệt, chạy Viết kịch bản. Hệ thống chỉ xử lý các ý tưởng đã đánh DUYET và chưa có kịch bản.","Mở KICH_BAN, đọc phần mở đầu, lời thoại hoặc chữ trên màn hình, diễn biến nội dung và lời kêu gọi hành động của từng video.","Sửa trực tiếp nội dung chưa phù hợp. Khi đã duyệt toàn bộ kịch bản, đổi DUYET_KICH_BAN trên KHACH_HANG thành Đã duyệt."],callout:{title:"Nguyên tắc nội dung",text:"Không bịa thành tích, giải thưởng, số liệu hoặc lời chứng thực. Nội dung chưa có bằng chứng phải được đánh dấu CAN_XAC_NHAN."},detailImages:[["m2-25.jpg"],["m2-26.jpg","m2-27.jpg"],["m2-28.jpg"]],calloutImages:[],defaultVideo:"/steps/videos/model2/full-a-z.mp4#t=620,750"},
  {id:"m2-buoc-08",n:"08",title:"Tạo kế hoạch hình từ đúng bộ ảnh thật",details:["Khi DUYET_KICH_BAN bằng Đã duyệt, chạy Tạo kế hoạch hình. Hệ thống đưa danh sách tên tệp ảnh thật vào câu lệnh gửi AI.","Mở KE_HOACH_HINH và kiểm tra từng cảnh: loại cảnh, mô tả hình, ảnh tham chiếu, công cụ và ghi chú sản xuất.","Tên ảnh tham chiếu phải tồn tại trong bộ ảnh của khách. Nếu tên không có thật, hệ thống phải ghi THIEU_ANH và nêu rõ ghi chú để người vận hành xử lý.","Chỉ sử dụng bốn loại cảnh CANH_SAN_PHAM, CANH_NHAN_VAT, CANH_MINH_HOA, CANH_DO_HOA và ba công cụ VEO, SEEDANCE, CAPCUT."],callout:{title:"Kết quả của bước",text:"Một kế hoạch hình có thể thực hiện từ đúng dữ liệu đã nhận, không tự tạo tên ảnh tham chiếu và không yêu cầu khách quay thêm video."},detailImages:[["m2-29.jpg"],["m2-30.jpg","m2-31.jpg"],["m2-31.jpg"],["m2-30.jpg"]],calloutImages:[],defaultVideo:"/steps/videos/model2/full-a-z.mp4#t=750,890"},
  {id:"m2-buoc-09",n:"09",title:"Đưa video hoàn thiện lên Drive và ghi kết quả QC",details:["Sau khi sản xuất, mở thư mục 04_VIDEO_FINAL và tải các video hoàn thiện lên đúng thư mục của khách.","Mở từng video để kiểm tra tệp phát được, đúng khung hình và đúng nội dung đã duyệt.","Chạy Ghi kết quả QC. Hệ thống đối chiếu danh sách trong SAN_XUAT với tệp thực tế trên Drive và giữ nguyên các cột QC bạn đã nhập tay.","Kiểm tra đủ số video của đợt và hoàn tất các cột duyệt cuối trước khi bàn giao."],callout:{title:"Không ghi đè đánh giá thủ công",text:"Việc quét lại tệp Drive chỉ cập nhật trạng thái tồn tại của video; các nhận xét QC đã nhập tay phải được giữ nguyên."},detailImages:[["m2-32.jpg","m2-33.jpg"],["m2-34.jpg"],["m2-35.jpg"],["m2-35.jpg"]],calloutImages:[],defaultVideo:"/steps/videos/model2/full-a-z.mp4#t=890,1000"},
  {id:"m2-buoc-10",n:"10",title:"Duyệt cuối và bàn giao video qua Gmail",details:["Chỉ khi DUYET_CUOI đúng bằng Đã duyệt gửi và số video thực tế đủ số lượng của đợt, chạy Bàn giao qua Gmail.","Đọc hộp xác nhận trước khi gửi. Hệ thống ghi ngày giao để không gửi lại cùng một đợt.","Mở Gmail kiểm tra thư bàn giao, mã khách, mã đợt giao và liên kết thư mục video final."],callout:{title:"Điểm chặn gửi thư",text:"Thiếu video hoặc chưa có trạng thái Đã duyệt gửi thì hệ thống phải dừng, không gửi một bộ video chưa hoàn chỉnh."},detailImages:[["m2-36.jpg"],["m2-36.jpg"],["m2-37.jpg"]],calloutImages:[],defaultVideo:"/steps/videos/model2/full-a-z.mp4#t=1000,1080"},
  {id:"m2-buoc-11",n:"11",title:"Đọc và phân loại thư phản hồi",details:["Khách trả lời trong chuỗi thư có mã khách. Hệ thống sử dụng mã này để nối phản hồi với đúng hồ sơ.","Chạy Đọc thư phản hồi. AI phân loại phản hồi thành LOI_CUNG_CAP, TRONG_VONG_SUA hoặc PHAT_SINH, kèm lý do và hành động đề xuất.","Mở PHAN_HOI để kiểm tra nội dung thư, nhóm phân loại và việc tiếp theo. AI không tự trả lời khách và không tự cam kết phạm vi sửa."],callout:{title:"Kết quả của bước",text:"Thư đã xử lý được gắn nhãn để không đọc trùng; người vận hành quyết định cách trả lời hoặc xử lý phát sinh."},detailImages:[["m2-38.jpg"],["m2-39.jpg"],["m2-40.jpg"]],calloutImages:[],defaultVideo:"/steps/videos/model2/full-a-z.mp4#t=1080,1170"},
  {id:"m2-buoc-12",n:"12",title:"Cập nhật menu và mở bảng điều khiển",details:["Sau khi dán hoặc sửa mã bảng điều khiển, kiểm tra Ma.gs vẫn là tệp duy nhất khai báo onOpen và menu San xuat video có mục Mở bảng điều khiển.","Chạy lại hàm cập nhật menu hoặc tải lại Google Sheets để menu mới xuất hiện.","Chọn Mở bảng điều khiển. Dashboard hiển thị các chặng đang mắc, thẻ khách hàng, thanh tiến độ, việc tiếp theo và nút chạy đúng bước.","Kiểm tra nút hành động trỏ đúng dòng khách trước khi gọi hàm nghiệp vụ. Phần máy chủ phải dùng switch tường minh, không dùng eval."],callout:{title:"Dashboard mở nhanh",text:"Hàm lấy dữ liệu bảng điều khiển chỉ đọc trang tính, không gọi Drive và không gọi API. Các thao tác nặng chỉ chạy khi bạn bấm nút của từng khách."},detailImages:[["m2-41.jpg"],["m2-40.jpg"],["m2-41.jpg"],["m2-41.jpg"]],calloutImages:[],defaultVideo:"/steps/videos/model2/full-a-z.mp4#t=1170,1292"}
];

